steps:
  - command: "./exitsim exit --code 0 --sleep 60"
    label: "sleep"

  - command: "go build -o exitsim . && ./exitsim exit --code 0"
    label: "exit 0"

  - command: "go build -o exitsim . && ./exitsim exit --code 1"
    label: "exit 1"

  - command: "go build -o exitsim . && ./exitsim exit --code 100"
    label: "exit 100"

  - command: "go build -o exitsim . && ./exitsim exit --code 255"
    label: "exit 255"

  - command: "go build -o exitsim . && ./exitsim signal --name sigterm"
    label: "sigterm"

  - command: "go build -o exitsim . && ./exitsim signal --name sigkill"
    label: "sigkill"
